## 통합데이터에 넣을 데이터 전처리

In [47]:
## 경고메세지 제거
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
df = pd.read_csv('경기도_태양광발전소설치현황.csv', encoding = 'euc-kr')
df.columns

Index(['허가기관명', '시군명', '용도', '세부용도', '사업상태', '발전소명', '소재지도로명주소', '소재지지번주소',
       '설비용량(KW)', '공급전압(V)', '주파수(Hz)', '사업허가일자', '사업개시예정일자', '사업개시일자',
       '소요부지면적(㎡)', '집광판면적(㎡)', '위도', '경도', '설치위치구분', '지목', '비고', '데이터기준일자'],
      dtype='object')

In [48]:
# 폰트 설정
import matplotlib.pyplot as plt
from matplotlib import font_manager

font_fname = 'C:\\Windows\\Fonts\\batang.ttc' # 바탕체 글꼴
font_family = font_manager.FontProperties(fname=font_fname).get_name()
plt.rcParams['font.family'] = font_family

In [49]:
# 라이브러리 임포트
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.model_selection import train_test_split

In [50]:
df['소재지지번주소']=df['소재지지번주소'].fillna(0.0)
df['소재지도로명주소']=df['소재지도로명주소'].fillna(0.0)
df['지목']=df['지목'].fillna('no')
df

,허가기관명,시군명,용도,세부용도,사업상태,발전소명,소재지도로명주소,소재지지번주소,설비용량(KW),공급전압(V),...,사업개시예정일자,사업개시일자,소요부지면적(㎡),집광판면적(㎡),위도,경도,설치위치구분,지목,비고,데이터기준일자
0,가평군,가평군,전기사업용,발전사업용,사업허가,(주)남창파워 태양광발전소,0.0,"경기도 가평군 북면 화악리 산 335-1 , 산336-1",98.55,380.0,...,NaN,NaN,2435.0,NaN,NaN,NaN,임야,임야,NaN,2022-06-14
1,가평군,가평군,전기사업용,발전사업용,사업허가,(주)남창파워 태양광발전소,0.0,"경기도 가평군 북면 화악리 산 335-1 , 산336-1",98.55,380.0,...,NaN,NaN,2435.0,NaN,NaN,NaN,임야,임야,NaN,2021-06-24
2,가평군,가평군,전기사업용,발전사업용,사업허가,180501-이곡1호 솔라 태양광발전소,0.0,경기도 가평군 북면 이곡리 344번지 1호,280.00,22900.0,...,NaN,NaN,2953.0,NaN,37.883787,127.529626,전,전,NaN,2021-06-24
3,가평군,가평군,전기사업용,발전사업용,사업허가,180501-이곡1호 솔라 태양광발전소,0.0,경기도 가평군 북면 이곡리 344번지 1호,280.00,22900.0,...,NaN,NaN,2953.0,NaN,NaN,NaN,전,전,NaN,2022-06-14
4,가평군,가평군,전기사업용,발전사업용,사업허가,180615-이곡6호 솔라 태양광발전소,0.0,"경기도 가평군 북면 이곡리 342 , 339-2, 339-7",150.12,380.0,...,NaN,NaN,2575.0,NaN,NaN,NaN,전,전,NaN,2022-06-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15726,화성시,화성시,전기사업용,발전사업용,운영중,희망8,경기도 화성시 장안면 화곡로,경기도 화성시 장안면 노진리,99.60,380.0,...,NaN,2021-10-27,NaN,NaN,NaN,NaN,건물,no,NaN,2022-05-20
15727,화성시,화성시,전기사업용,발전사업용,사업허가,희망9,경기도 화성시 장안면 화곡로,경기도 화성시 장안면 노진리,99.60,380.0,...,NaN,NaN,NaN,NaN,NaN,NaN,건물,no,NaN,2020-11-26
15728,화성시,화성시,전기사업용,발전사업용,운영중,희망9,경기도 화성시 장안면 화곡로,경기도 화성시 장안면 노진리,99.60,380.0,...,NaN,2021-10-27,NaN,NaN,NaN,NaN,건물,no,NaN,2022-05-20
15729,화성시,화성시,전기사업용,발전사업용,운영중,히즈시스템1호태양광발전소,경기도 화성시 송산산단길,경기도 화성시 송산면 지화,89.60,380.0,...,NaN,2021-10-26,NaN,NaN,NaN,NaN,건물위,no,NaN,2022-05-20
15730,화성시,화성시,전기사업용,발전사업용,운영중,히즈시스템2호태양광발전소,경기도 화성시 송산산단길,경기도 화성시 송산면 지화,80.00,380.0,...,NaN,2021-10-26,NaN,NaN,NaN,NaN,건물위,no,NaN,2022-05-20

In [51]:
# 포함하고자 하는 문자열 리스트 생성
list = ['임야','구거','도로','하천','철도','임','전','목장','과수원','답','목']

new_df=pd.DataFrame()
for i in list:
    df1=df.loc[df['지목'].str.contains(i)]
    new_df=new_df.append(df1,ignore_index=True)
new_df

,허가기관명,시군명,용도,세부용도,사업상태,발전소명,소재지도로명주소,소재지지번주소,설비용량(KW),공급전압(V),...,사업개시예정일자,사업개시일자,소요부지면적(㎡),집광판면적(㎡),위도,경도,설치위치구분,지목,비고,데이터기준일자
0,가평군,가평군,전기사업용,발전사업용,사업허가,(주)남창파워 태양광발전소,0.0,"경기도 가평군 북면 화악리 산 335-1 , 산336-1",98.55,380.0,...,NaN,NaN,2435.0,NaN,NaN,NaN,임야,임야,NaN,2022-06-14
1,가평군,가평군,전기사업용,발전사업용,사업허가,(주)남창파워 태양광발전소,0.0,"경기도 가평군 북면 화악리 산 335-1 , 산336-1",98.55,380.0,...,NaN,NaN,2435.0,NaN,NaN,NaN,임야,임야,NaN,2021-06-24
2,가평군,가평군,전기사업용,발전사업용,허가취소,CHK 태양광발전소,0.0,"경기도 가평군 북면 목동리 237-11 , 107",400.00,22900.0,...,NaN,NaN,5280.0,NaN,37.915443,127.594570,임야,임야,NaN,2022-06-14
3,가평군,가평군,전기사업용,발전사업용,허가취소,CHK 태양광발전소,0.0,"경기도 가평군 북면 목동리 237-11 , 107",400.00,22900.0,...,NaN,NaN,5280.0,NaN,37.915443,127.594570,임야,임야,NaN,2021-06-24
4,가평군,가평군,전기사업용,발전사업용,사업허가,가평85 태양광발전소,0.0,경기도 가평군 가평읍 하색리 산 57-1,97.20,380.0,...,NaN,NaN,1750.0,NaN,37.820654,127.475502,NaN,임야,NaN,2021-06-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1976,이천시,이천시,전기사업용,발전사업용,사업허가,창규 태양광발전소,0.0,경기도 이천시 백사면 송말리 594번지 1호,87.60,380.0,...,2020-11-24,NaN,NaN,NaN,37.345337,127.479994,건물,목장,NaN,2021-06-02
1977,이천시,이천시,전기사업용,발전사업용,허가취소,태성농장태양광발전소,0.0,경기도 이천시 설성면 설가로321번길 116-90,95.04,380.0,...,NaN,NaN,NaN,NaN,37.166942,127.503526,건물,목장용지,NaN,2021-06-02
1978,이천시,이천시,전기사업용,발전사업용,사업허가,한사랑가온누리 태양광발전소,0.0,"경기도 이천시 장호원읍 송산리 673번지 5호 ,673-15,673-7,673-14...",199.29,380.0,...,2020-12-03,NaN,NaN,NaN,37.115984,127.578649,건,"전,목장",NaN,2021-06-02
1979,이천시,이천시,전기사업용,발전사업용,사업허가,한사랑온새미로 태양광발전소,0.0,"경기도 이천시 장호원읍 송산리 673번지 7호 ,673-13,673-14",199.29,380.0,...,2020-12-03,NaN,NaN,NaN,37.115462,127.578701,건,목장,NaN,2021-06-02
1980,이천시,이천시,전기사업용,발전사업용,허가취소,호법면 단천리 태양광발전소,0.0,경기도 이천시 호법면 단천리 171,49.50,220.0,...,NaN,NaN,NaN,NaN,37.229546,127.409095,기타,목장용지,NaN,2021-06-02

In [52]:
data1=new_df[['시군명','소요부지면적(㎡)']]
data1

      시군명  소요부지면적(㎡)
0     가평군     2435.0
1     가평군     2435.0
2     가평군     5280.0
3     가평군     5280.0
4     가평군     1750.0
...   ...        ...
1976  이천시        NaN
1977  이천시        NaN
1978  이천시        NaN
1979  이천시        NaN
1980  이천시        NaN

[1981 rows x 2 columns]

In [57]:
data1.groupby('시군명')['소요부지면적(㎡)'].sum()

시군명
가평군     482828.040
고양시      47179.600
과천시          0.000
광주시      11604.000
군포시        660.000
동두천시         0.000
수원시      22729.000
시흥시       2534.410
안산시          0.000
양주시          0.000
양평군     328387.748
연천군     990101.540
이천시          0.000
하남시          0.000
Name: 소요부지면적(㎡), dtype: float64

In [60]:
dff = pd.read_csv('산사태발생.csv', encoding = 'euc-kr')
dff

     산사태피해면적       산사태재해명  산사태재해년도 시군구명  읍면명
0       3.15  7.28.~8.11.     2020  양평군  단월면
1       2.57  7.28.~8.11.     2020  양평군  단월면
2       2.28  7.28.~8.11.     2020  양평군  단월면
3       2.19  7.28.~8.11.     2020  양평군  단월면
4       1.96  7.28.~8.11.     2020  이천시  호법면
..       ...          ...      ...  ...  ...
243     0.10   8.26.~9.1.     2018  양주시   남면
244     0.02   8.26.~9.1.     2018  양주시   남면
245     1.50   8.26.~9.1.     2018  양주시   남면
246     0.05   8.26.~9.1.     2018  양주시   남면
247     0.16   8.26.~9.1.     2018  김포시  대곶면

[248 rows x 5 columns]

In [61]:
dfff=dff[['시군구명','산사태피해면적']]
dfff

    시군구명  산사태피해면적
0    양평군     3.15
1    양평군     2.57
2    양평군     2.28
3    양평군     2.19
4    이천시     1.96
..   ...      ...
243  양주시     0.10
244  양주시     0.02
245  양주시     1.50
246  양주시     0.05
247  김포시     0.16

[248 rows x 2 columns]

In [63]:
dfff.groupby('시군구명')['산사태피해면적'].sum()

시군구명
가평군        15.13
김포시         0.55
남양주시        0.05
안성시        78.33
양주시         4.71
양평군        14.42
여주시         0.03
연천군         5.58
용인시 수지구     0.15
용인시 처인구    14.98
이천시        32.80
파주시         0.16
평택시         0.06
포천시         0.46
하남시         0.04
Name: 산사태피해면적, dtype: float64

In [65]:
dfff.groupby(['시군구명']).count()

         산사태피해면적
시군구명
가평군           19
김포시            3
남양주시           1
안성시           94
양주시           10
양평군           16
여주시            2
연천군           24
용인시 수지구        1
용인시 처인구       24
이천시           45
파주시            2
평택시            1
포천시            5
하남시            1